//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaavoniUT3SMSManager.FarapayamakRecvService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagesBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessagesBL : TaavoniUT3SMSManager.FarapayamakRecvService.BaseBL {
        
        private long MsgIDField;
        
        private int UserIDField;
        
        private int LinkIDField;
        
        private int NumberIDField;
        
        private double TariffField;
        
        private byte MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdhField;
        
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        private int FirstLocationField;
        
        private int CurrentLocationField;
        
        private int PartsField;
        
        private bool IsFlashField;
        
        private bool IsReadField;
        
        private bool IsUnicodeField;
        
        private double CreditField;
        
        private int ModuleField;
        
        private int RecCountField;
        
        private int RecFailedField;
        
        private int RecSuccessField;
        
        private bool IsMoneyBackField;
        
        private int UserStepedMasterField;
        
        private int UserMasterField;
        
        private int MoneyBackCountField;
        
        private int MoneyBackLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MsgID {
            get {
                return this.MsgIDField;
            }
            set {
                if ((this.MsgIDField.Equals(value) != true)) {
                    this.MsgIDField = value;
                    this.RaisePropertyChanged("MsgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int LinkID {
            get {
                return this.LinkIDField;
            }
            set {
                if ((this.LinkIDField.Equals(value) != true)) {
                    this.LinkIDField = value;
                    this.RaisePropertyChanged("LinkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumberID {
            get {
                return this.NumberIDField;
            }
            set {
                if ((this.NumberIDField.Equals(value) != true)) {
                    this.NumberIDField = value;
                    this.RaisePropertyChanged("NumberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Tariff {
            get {
                return this.TariffField;
            }
            set {
                if ((this.TariffField.Equals(value) != true)) {
                    this.TariffField = value;
                    this.RaisePropertyChanged("Tariff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((this.MsgTypeField.Equals(value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Udh {
            get {
                return this.UdhField;
            }
            set {
                if ((object.ReferenceEquals(this.UdhField, value) != true)) {
                    this.UdhField = value;
                    this.RaisePropertyChanged("Udh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int FirstLocation {
            get {
                return this.FirstLocationField;
            }
            set {
                if ((this.FirstLocationField.Equals(value) != true)) {
                    this.FirstLocationField = value;
                    this.RaisePropertyChanged("FirstLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((this.CurrentLocationField.Equals(value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((this.PartsField.Equals(value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool IsFlash {
            get {
                return this.IsFlashField;
            }
            set {
                if ((this.IsFlashField.Equals(value) != true)) {
                    this.IsFlashField = value;
                    this.RaisePropertyChanged("IsFlash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((this.IsUnicodeField.Equals(value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int RecCount {
            get {
                return this.RecCountField;
            }
            set {
                if ((this.RecCountField.Equals(value) != true)) {
                    this.RecCountField = value;
                    this.RaisePropertyChanged("RecCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int RecFailed {
            get {
                return this.RecFailedField;
            }
            set {
                if ((this.RecFailedField.Equals(value) != true)) {
                    this.RecFailedField = value;
                    this.RaisePropertyChanged("RecFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int RecSuccess {
            get {
                return this.RecSuccessField;
            }
            set {
                if ((this.RecSuccessField.Equals(value) != true)) {
                    this.RecSuccessField = value;
                    this.RaisePropertyChanged("RecSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public bool IsMoneyBack {
            get {
                return this.IsMoneyBackField;
            }
            set {
                if ((this.IsMoneyBackField.Equals(value) != true)) {
                    this.IsMoneyBackField = value;
                    this.RaisePropertyChanged("IsMoneyBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int UserStepedMaster {
            get {
                return this.UserStepedMasterField;
            }
            set {
                if ((this.UserStepedMasterField.Equals(value) != true)) {
                    this.UserStepedMasterField = value;
                    this.RaisePropertyChanged("UserStepedMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int UserMaster {
            get {
                return this.UserMasterField;
            }
            set {
                if ((this.UserMasterField.Equals(value) != true)) {
                    this.UserMasterField = value;
                    this.RaisePropertyChanged("UserMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public int MoneyBackCount {
            get {
                return this.MoneyBackCountField;
            }
            set {
                if ((this.MoneyBackCountField.Equals(value) != true)) {
                    this.MoneyBackCountField = value;
                    this.RaisePropertyChanged("MoneyBackCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public int MoneyBackLevel {
            get {
                return this.MoneyBackLevelField;
            }
            set {
                if ((this.MoneyBackLevelField.Equals(value) != true)) {
                    this.MoneyBackLevelField = value;
                    this.RaisePropertyChanged("MoneyBackLevel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL))]
    public partial class BaseBL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageLocation", Namespace="http://tempuri.org/")]
    public enum MessageLocation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Received = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Removed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgReceptions", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MsgReceptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecNumber {
            get {
                return this.RecNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RecNumberField, value) != true)) {
                    this.RecNumberField = value;
                    this.RaisePropertyChanged("RecNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SendDateField, value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RecStatus {
            get {
                return this.RecStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.RecStatusField, value) != true)) {
                    this.RecStatusField = value;
                    this.RaisePropertyChanged("RecStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DeliveryStatus {
            get {
                return this.DeliveryStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStatusField, value) != true)) {
                    this.DeliveryStatusField = value;
                    this.RaisePropertyChanged("DeliveryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RecID {
            get {
                return this.RecIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RecIDField, value) != true)) {
                    this.RecIDField = value;
                    this.RaisePropertyChanged("RecID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FarapayamakRecvService.ReceiveSoap")]
    public interface ReceiveSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountResponse GetInboxCount(TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesResponse GetMessages(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesWithChangeIsRead", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadResponse GetMessagesWithChangeIsRead(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeMessageIsRead", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadResponse ChangeMessageIsRead(TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesByDate", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateResponse GetMessagesByDate(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersMessagesByDate", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateResponse GetUsersMessagesByDate(TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageStr", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrResponse GetMessageStr(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveMessages", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesResponse RemoveMessages(TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesReceptions", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsResponse GetMessagesReceptions(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCount", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequestBody Body;
        
        public GetInboxCountRequest() {
        }
        
        public GetInboxCountRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isRead;
        
        public GetInboxCountRequestBody() {
        }
        
        public GetInboxCountRequestBody(string username, string password, bool isRead) {
            this.username = username;
            this.password = password;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountResponseBody Body;
        
        public GetInboxCountResponse() {
        }
        
        public GetInboxCountResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetInboxCountResult;
        
        public GetInboxCountResponseBody() {
        }
        
        public GetInboxCountResponseBody(int GetInboxCountResult) {
            this.GetInboxCountResult = GetInboxCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string username, string password, int location, string from, int index, int count) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesWithChangeIsReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesWithChangeIsRead", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequestBody Body;
        
        public GetMessagesWithChangeIsReadRequest() {
        }
        
        public GetMessagesWithChangeIsReadRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesWithChangeIsReadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool isRead;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool changeIsRead;
        
        public GetMessagesWithChangeIsReadRequestBody() {
        }
        
        public GetMessagesWithChangeIsReadRequestBody(string username, string password, int location, string from, int index, int count, bool isRead, bool changeIsRead) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
            this.isRead = isRead;
            this.changeIsRead = changeIsRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesWithChangeIsReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesWithChangeIsReadResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadResponseBody Body;
        
        public GetMessagesWithChangeIsReadResponse() {
        }
        
        public GetMessagesWithChangeIsReadResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesWithChangeIsReadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesWithChangeIsReadResult;
        
        public GetMessagesWithChangeIsReadResponseBody() {
        }
        
        public GetMessagesWithChangeIsReadResponseBody(TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesWithChangeIsReadResult) {
            this.GetMessagesWithChangeIsReadResult = GetMessagesWithChangeIsReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeMessageIsReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeMessageIsRead", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequestBody Body;
        
        public ChangeMessageIsReadRequest() {
        }
        
        public ChangeMessageIsReadRequest(TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeMessageIsReadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msgIds;
        
        public ChangeMessageIsReadRequestBody() {
        }
        
        public ChangeMessageIsReadRequestBody(string username, string password, string msgIds) {
            this.username = username;
            this.password = password;
            this.msgIds = msgIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeMessageIsReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeMessageIsReadResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadResponseBody Body;
        
        public ChangeMessageIsReadResponse() {
        }
        
        public ChangeMessageIsReadResponse(TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeMessageIsReadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChangeMessageIsReadResult;
        
        public ChangeMessageIsReadResponseBody() {
        }
        
        public ChangeMessageIsReadResponseBody(int ChangeMessageIsReadResult) {
            this.ChangeMessageIsReadResult = ChangeMessageIsReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesByDate", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequestBody Body;
        
        public GetMessagesByDateRequest() {
        }
        
        public GetMessagesByDateRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime dateTo;
        
        public GetMessagesByDateRequestBody() {
        }
        
        public GetMessagesByDateRequestBody(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateResponseBody Body;
        
        public GetMessagesByDateResponse() {
        }
        
        public GetMessagesByDateResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesByDateResult;
        
        public GetMessagesByDateResponseBody() {
        }
        
        public GetMessagesByDateResponseBody(TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesByDateResult) {
            this.GetMessagesByDateResult = GetMessagesByDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersMessagesByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersMessagesByDate", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequestBody Body;
        
        public GetUsersMessagesByDateRequest() {
        }
        
        public GetUsersMessagesByDateRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersMessagesByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime dateTo;
        
        public GetUsersMessagesByDateRequestBody() {
        }
        
        public GetUsersMessagesByDateRequestBody(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersMessagesByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersMessagesByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateResponseBody Body;
        
        public GetUsersMessagesByDateResponse() {
        }
        
        public GetUsersMessagesByDateResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersMessagesByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetUsersMessagesByDateResult;
        
        public GetUsersMessagesByDateResponseBody() {
        }
        
        public GetUsersMessagesByDateResponseBody(TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetUsersMessagesByDateResult) {
            this.GetUsersMessagesByDateResult = GetUsersMessagesByDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStr", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequestBody Body;
        
        public GetMessageStrRequest() {
        }
        
        public GetMessageStrRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public GetMessageStrRequestBody() {
        }
        
        public GetMessageStrRequestBody(string username, string password, int location, string from, int index, int count) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStrResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrResponseBody Body;
        
        public GetMessageStrResponse() {
        }
        
        public GetMessageStrResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessageStrResult;
        
        public GetMessageStrResponseBody() {
        }
        
        public GetMessageStrResponseBody(string GetMessageStrResult) {
            this.GetMessageStrResult = GetMessageStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveMessages", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequestBody Body;
        
        public RemoveMessagesRequest() {
        }
        
        public RemoveMessagesRequest(TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessageLocation location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgIds;
        
        public RemoveMessagesRequestBody() {
        }
        
        public RemoveMessagesRequestBody(string username, string password, TaavoniUT3SMSManager.FarapayamakRecvService.MessageLocation location, string msgIds) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.msgIds = msgIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesResponseBody Body;
        
        public RemoveMessagesResponse() {
        }
        
        public RemoveMessagesResponse(TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveMessagesResult;
        
        public RemoveMessagesResponseBody() {
        }
        
        public RemoveMessagesResponseBody(int RemoveMessagesResult) {
            this.RemoveMessagesResult = RemoveMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesReceptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesReceptions", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequestBody Body;
        
        public GetMessagesReceptionsRequest() {
        }
        
        public GetMessagesReceptionsRequest(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesReceptionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int fromRows;
        
        public GetMessagesReceptionsRequestBody() {
        }
        
        public GetMessagesReceptionsRequestBody(string username, string password, int msgId, int fromRows) {
            this.username = username;
            this.password = password;
            this.msgId = msgId;
            this.fromRows = fromRows;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesReceptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesReceptionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsResponseBody Body;
        
        public GetMessagesReceptionsResponse() {
        }
        
        public GetMessagesReceptionsResponse(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesReceptionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakRecvService.MsgReceptions[] GetMessagesReceptionsResult;
        
        public GetMessagesReceptionsResponseBody() {
        }
        
        public GetMessagesReceptionsResponseBody(TaavoniUT3SMSManager.FarapayamakRecvService.MsgReceptions[] GetMessagesReceptionsResult) {
            this.GetMessagesReceptionsResult = GetMessagesReceptionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceiveSoapChannel : TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveSoapClient : System.ServiceModel.ClientBase<TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap>, TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap {
        
        public ReceiveSoapClient() {
        }
        
        public ReceiveSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetInboxCount(TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequest request) {
            return base.Channel.GetInboxCount(request);
        }
        
        public int GetInboxCount(string username, string password, bool isRead) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.isRead = isRead;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetInboxCountResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetInboxCount(inValue);
            return retVal.Body.GetInboxCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetMessages(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessages(string username, string password, int location, string from, int index, int count) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetMessagesWithChangeIsRead(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequest request) {
            return base.Channel.GetMessagesWithChangeIsRead(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesWithChangeIsRead(string username, string password, int location, string from, int index, int count, bool isRead, bool changeIsRead) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            inValue.Body.isRead = isRead;
            inValue.Body.changeIsRead = changeIsRead;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesWithChangeIsReadResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetMessagesWithChangeIsRead(inValue);
            return retVal.Body.GetMessagesWithChangeIsReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.ChangeMessageIsRead(TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequest request) {
            return base.Channel.ChangeMessageIsRead(request);
        }
        
        public int ChangeMessageIsRead(string username, string password, string msgIds) {
            TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgIds = msgIds;
            TaavoniUT3SMSManager.FarapayamakRecvService.ChangeMessageIsReadResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).ChangeMessageIsRead(inValue);
            return retVal.Body.ChangeMessageIsReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetMessagesByDate(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequest request) {
            return base.Channel.GetMessagesByDate(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetMessagesByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesByDateResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetMessagesByDate(inValue);
            return retVal.Body.GetMessagesByDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetUsersMessagesByDate(TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequest request) {
            return base.Channel.GetUsersMessagesByDate(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakRecvService.MessagesBL[] GetUsersMessagesByDate(string username, string password, int location, string from, int index, int count, System.DateTime dateFrom, System.DateTime dateTo) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetUsersMessagesByDateResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetUsersMessagesByDate(inValue);
            return retVal.Body.GetUsersMessagesByDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetMessageStr(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequest request) {
            return base.Channel.GetMessageStr(request);
        }
        
        public string GetMessageStr(string username, string password, int location, string from, int index, int count) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessageStrResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetMessageStr(inValue);
            return retVal.Body.GetMessageStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.RemoveMessages(TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequest request) {
            return base.Channel.RemoveMessages(request);
        }
        
        public int RemoveMessages(string username, string password, TaavoniUT3SMSManager.FarapayamakRecvService.MessageLocation location, string msgIds) {
            TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.msgIds = msgIds;
            TaavoniUT3SMSManager.FarapayamakRecvService.RemoveMessagesResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).RemoveMessages(inValue);
            return retVal.Body.RemoveMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsResponse TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap.GetMessagesReceptions(TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequest request) {
            return base.Channel.GetMessagesReceptions(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakRecvService.MsgReceptions[] GetMessagesReceptions(string username, string password, int msgId, int fromRows) {
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequest inValue = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgId = msgId;
            inValue.Body.fromRows = fromRows;
            TaavoniUT3SMSManager.FarapayamakRecvService.GetMessagesReceptionsResponse retVal = ((TaavoniUT3SMSManager.FarapayamakRecvService.ReceiveSoap)(this)).GetMessagesReceptions(inValue);
            return retVal.Body.GetMessagesReceptionsResult;
        }
    }
}
