//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaavoniUT3SMSManager.FarapayamakSend {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagesBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessagesBL : TaavoniUT3SMSManager.FarapayamakSend.BaseBL {
        
        private long MsgIDField;
        
        private int UserIDField;
        
        private int LinkIDField;
        
        private int NumberIDField;
        
        private double TariffField;
        
        private byte MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdhField;
        
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        private int FirstLocationField;
        
        private int CurrentLocationField;
        
        private int PartsField;
        
        private bool IsFlashField;
        
        private bool IsReadField;
        
        private bool IsUnicodeField;
        
        private double CreditField;
        
        private int ModuleField;
        
        private int RecCountField;
        
        private int RecFailedField;
        
        private int RecSuccessField;
        
        private bool IsMoneyBackField;
        
        private int UserStepedMasterField;
        
        private int UserMasterField;
        
        private int MoneyBackCountField;
        
        private int MoneyBackLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MsgID {
            get {
                return this.MsgIDField;
            }
            set {
                if ((this.MsgIDField.Equals(value) != true)) {
                    this.MsgIDField = value;
                    this.RaisePropertyChanged("MsgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int LinkID {
            get {
                return this.LinkIDField;
            }
            set {
                if ((this.LinkIDField.Equals(value) != true)) {
                    this.LinkIDField = value;
                    this.RaisePropertyChanged("LinkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumberID {
            get {
                return this.NumberIDField;
            }
            set {
                if ((this.NumberIDField.Equals(value) != true)) {
                    this.NumberIDField = value;
                    this.RaisePropertyChanged("NumberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Tariff {
            get {
                return this.TariffField;
            }
            set {
                if ((this.TariffField.Equals(value) != true)) {
                    this.TariffField = value;
                    this.RaisePropertyChanged("Tariff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte MsgType {
            get {
                return this.MsgTypeField;
            }
            set {
                if ((this.MsgTypeField.Equals(value) != true)) {
                    this.MsgTypeField = value;
                    this.RaisePropertyChanged("MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Udh {
            get {
                return this.UdhField;
            }
            set {
                if ((object.ReferenceEquals(this.UdhField, value) != true)) {
                    this.UdhField = value;
                    this.RaisePropertyChanged("Udh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int FirstLocation {
            get {
                return this.FirstLocationField;
            }
            set {
                if ((this.FirstLocationField.Equals(value) != true)) {
                    this.FirstLocationField = value;
                    this.RaisePropertyChanged("FirstLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CurrentLocation {
            get {
                return this.CurrentLocationField;
            }
            set {
                if ((this.CurrentLocationField.Equals(value) != true)) {
                    this.CurrentLocationField = value;
                    this.RaisePropertyChanged("CurrentLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((this.PartsField.Equals(value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool IsFlash {
            get {
                return this.IsFlashField;
            }
            set {
                if ((this.IsFlashField.Equals(value) != true)) {
                    this.IsFlashField = value;
                    this.RaisePropertyChanged("IsFlash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((this.IsUnicodeField.Equals(value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int RecCount {
            get {
                return this.RecCountField;
            }
            set {
                if ((this.RecCountField.Equals(value) != true)) {
                    this.RecCountField = value;
                    this.RaisePropertyChanged("RecCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int RecFailed {
            get {
                return this.RecFailedField;
            }
            set {
                if ((this.RecFailedField.Equals(value) != true)) {
                    this.RecFailedField = value;
                    this.RaisePropertyChanged("RecFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int RecSuccess {
            get {
                return this.RecSuccessField;
            }
            set {
                if ((this.RecSuccessField.Equals(value) != true)) {
                    this.RecSuccessField = value;
                    this.RaisePropertyChanged("RecSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public bool IsMoneyBack {
            get {
                return this.IsMoneyBackField;
            }
            set {
                if ((this.IsMoneyBackField.Equals(value) != true)) {
                    this.IsMoneyBackField = value;
                    this.RaisePropertyChanged("IsMoneyBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int UserStepedMaster {
            get {
                return this.UserStepedMasterField;
            }
            set {
                if ((this.UserStepedMasterField.Equals(value) != true)) {
                    this.UserStepedMasterField = value;
                    this.RaisePropertyChanged("UserStepedMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int UserMaster {
            get {
                return this.UserMasterField;
            }
            set {
                if ((this.UserMasterField.Equals(value) != true)) {
                    this.UserMasterField = value;
                    this.RaisePropertyChanged("UserMaster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public int MoneyBackCount {
            get {
                return this.MoneyBackCountField;
            }
            set {
                if ((this.MoneyBackCountField.Equals(value) != true)) {
                    this.MoneyBackCountField = value;
                    this.RaisePropertyChanged("MoneyBackCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public int MoneyBackLevel {
            get {
                return this.MoneyBackLevelField;
            }
            set {
                if ((this.MoneyBackLevelField.Equals(value) != true)) {
                    this.MoneyBackLevelField = value;
                    this.RaisePropertyChanged("MoneyBackLevel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TaavoniUT3SMSManager.FarapayamakSend.MessagesBL))]
    public partial class BaseBL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FarapayamakSend.SendSoap")]
    public interface SendSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSResponse SendSimpleSMS(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS2", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Response SendSimpleSMS2(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Request request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.SendSmsResponse SendSms(TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWithDomain", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainResponse SendWithDomain(TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsPrice", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceResponse GetSmsPrice(TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetCreditResponse GetCredit(TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        int GetDelivery(long recId);
        
        // CODEGEN: Generating message contract since element name recId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery2", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Response GetDelivery2(TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Request request);
        
        // CODEGEN: Generating message contract since element name recId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryResponse GetMultiDelivery(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name recId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery2", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Response GetMultiDelivery2(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Request request);
        
        // CODEGEN: Generating message contract since element name recIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesResponse GetDeliveries(TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountResponse GetInboxCount(TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
        TaavoniUT3SMSManager.FarapayamakSend.getMessagesResponse getMessages(TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMS", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequestBody Body;
        
        public SendSimpleSMSRequest() {
        }
        
        public SendSimpleSMSRequest(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        public SendSimpleSMSRequestBody() {
        }
        
        public SendSimpleSMSRequestBody(string username, string password, TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString to, string from, string text, bool isflash) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSResponseBody Body;
        
        public SendSimpleSMSResponse() {
        }
        
        public SendSimpleSMSResponse(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString SendSimpleSMSResult;
        
        public SendSimpleSMSResponseBody() {
        }
        
        public SendSimpleSMSResponseBody(TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString SendSimpleSMSResult) {
            this.SendSimpleSMSResult = SendSimpleSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMS2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMS2", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2RequestBody Body;
        
        public SendSimpleSMS2Request() {
        }
        
        public SendSimpleSMS2Request(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMS2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        public SendSimpleSMS2RequestBody() {
        }
        
        public SendSimpleSMS2RequestBody(string username, string password, string to, string from, string text, bool isflash) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSimpleSMS2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSimpleSMS2Response", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2ResponseBody Body;
        
        public SendSimpleSMS2Response() {
        }
        
        public SendSimpleSMS2Response(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSimpleSMS2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSimpleSMS2Result;
        
        public SendSimpleSMS2ResponseBody() {
        }
        
        public SendSimpleSMS2ResponseBody(string SendSimpleSMS2Result) {
            this.SendSimpleSMS2Result = SendSimpleSMS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] status;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string username, string password, TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString to, string from, string text, bool isflash, string udh, TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(TaavoniUT3SMSManager.FarapayamakSend.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] status;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(int SendSmsResult, TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recId, byte[] status) {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWithDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWithDomain", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequestBody Body;
        
        public SendWithDomainRequest() {
        }
        
        public SendWithDomainRequest(TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWithDomainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string domainName;
        
        public SendWithDomainRequestBody() {
        }
        
        public SendWithDomainRequestBody(string username, string password, string to, string from, string text, bool isflash, string domainName) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.domainName = domainName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWithDomainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWithDomainResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainResponseBody Body;
        
        public SendWithDomainResponse() {
        }
        
        public SendWithDomainResponse(TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWithDomainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWithDomainResult;
        
        public SendWithDomainResponseBody() {
        }
        
        public SendWithDomainResponseBody(string SendWithDomainResult) {
            this.SendWithDomainResult = SendWithDomainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsPrice", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequestBody Body;
        
        public GetSmsPriceRequest() {
        }
        
        public GetSmsPriceRequest(TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int irancellCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int mtnCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string text;
        
        public GetSmsPriceRequestBody() {
        }
        
        public GetSmsPriceRequestBody(string username, string password, int irancellCount, int mtnCount, string from, string text) {
            this.username = username;
            this.password = password;
            this.irancellCount = irancellCount;
            this.mtnCount = mtnCount;
            this.from = from;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceResponseBody Body;
        
        public GetSmsPriceResponse() {
        }
        
        public GetSmsPriceResponse(TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetSmsPriceResult;
        
        public GetSmsPriceResponseBody() {
        }
        
        public GetSmsPriceResponseBody(double GetSmsPriceResult) {
            this.GetSmsPriceResult = GetSmsPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequestBody Body;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody() {
        }
        
        public GetCreditRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetCreditResponseBody Body;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(TaavoniUT3SMSManager.FarapayamakSend.GetCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody() {
        }
        
        public GetCreditResponseBody(double GetCreditResult) {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDelivery2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDelivery2", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2RequestBody Body;
        
        public GetDelivery2Request() {
        }
        
        public GetDelivery2Request(TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDelivery2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recId;
        
        public GetDelivery2RequestBody() {
        }
        
        public GetDelivery2RequestBody(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDelivery2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDelivery2Response", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2ResponseBody Body;
        
        public GetDelivery2Response() {
        }
        
        public GetDelivery2Response(TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDelivery2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDelivery2Result;
        
        public GetDelivery2ResponseBody() {
        }
        
        public GetDelivery2ResponseBody(int GetDelivery2Result) {
            this.GetDelivery2Result = GetDelivery2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMultiDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMultiDelivery", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequestBody Body;
        
        public GetMultiDeliveryRequest() {
        }
        
        public GetMultiDeliveryRequest(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMultiDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recId;
        
        public GetMultiDeliveryRequestBody() {
        }
        
        public GetMultiDeliveryRequestBody(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMultiDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMultiDeliveryResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryResponseBody Body;
        
        public GetMultiDeliveryResponse() {
        }
        
        public GetMultiDeliveryResponse(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMultiDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMultiDeliveryResult;
        
        public GetMultiDeliveryResponseBody() {
        }
        
        public GetMultiDeliveryResponseBody(byte[] GetMultiDeliveryResult) {
            this.GetMultiDeliveryResult = GetMultiDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMultiDelivery2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMultiDelivery2", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2RequestBody Body;
        
        public GetMultiDelivery2Request() {
        }
        
        public GetMultiDelivery2Request(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMultiDelivery2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recId;
        
        public GetMultiDelivery2RequestBody() {
        }
        
        public GetMultiDelivery2RequestBody(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMultiDelivery2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMultiDelivery2Response", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2ResponseBody Body;
        
        public GetMultiDelivery2Response() {
        }
        
        public GetMultiDelivery2Response(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMultiDelivery2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString GetMultiDelivery2Result;
        
        public GetMultiDelivery2ResponseBody() {
        }
        
        public GetMultiDelivery2ResponseBody(TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString GetMultiDelivery2Result) {
            this.GetMultiDelivery2Result = GetMultiDelivery2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveries", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequestBody Body;
        
        public GetDeliveriesRequest() {
        }
        
        public GetDeliveriesRequest(TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeliveriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetDeliveriesRequestBody() {
        }
        
        public GetDeliveriesRequestBody(TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recIds, string username, string password) {
            this.recIds = recIds;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesResponseBody Body;
        
        public GetDeliveriesResponse() {
        }
        
        public GetDeliveriesResponse(TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeliveriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfInt GetDeliveriesResult;
        
        public GetDeliveriesResponseBody() {
        }
        
        public GetDeliveriesResponseBody(TaavoniUT3SMSManager.FarapayamakSend.ArrayOfInt GetDeliveriesResult) {
            this.GetDeliveriesResult = GetDeliveriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCount", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequestBody Body;
        
        public GetInboxCountRequest() {
        }
        
        public GetInboxCountRequest(TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isRead;
        
        public GetInboxCountRequestBody() {
        }
        
        public GetInboxCountRequestBody(string username, string password, bool isRead) {
            this.username = username;
            this.password = password;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountResponseBody Body;
        
        public GetInboxCountResponse() {
        }
        
        public GetInboxCountResponse(TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInboxCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetInboxCountResult;
        
        public GetInboxCountResponseBody() {
        }
        
        public GetInboxCountResponseBody(int GetInboxCountResult) {
            this.GetInboxCountResult = GetInboxCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessages", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequestBody Body;
        
        public getMessagesRequest() {
        }
        
        public getMessagesRequest(TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int count;
        
        public getMessagesRequestBody() {
        }
        
        public getMessagesRequestBody(string username, string password, int location, string from, int index, int count) {
            this.username = username;
            this.password = password;
            this.location = location;
            this.from = from;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.getMessagesResponseBody Body;
        
        public getMessagesResponse() {
        }
        
        public getMessagesResponse(TaavoniUT3SMSManager.FarapayamakSend.getMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.FarapayamakSend.MessagesBL[] getMessagesResult;
        
        public getMessagesResponseBody() {
        }
        
        public getMessagesResponseBody(TaavoniUT3SMSManager.FarapayamakSend.MessagesBL[] getMessagesResult) {
            this.getMessagesResult = getMessagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSoapChannel : TaavoniUT3SMSManager.FarapayamakSend.SendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<TaavoniUT3SMSManager.FarapayamakSend.SendSoap>, TaavoniUT3SMSManager.FarapayamakSend.SendSoap {
        
        public SendSoapClient() {
        }
        
        public SendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.SendSimpleSMS(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequest request) {
            return base.Channel.SendSimpleSMS(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString SendSimpleSMS(string username, string password, TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString to, string from, string text, bool isflash) {
            TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMSResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).SendSimpleSMS(inValue);
            return retVal.Body.SendSimpleSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Response TaavoniUT3SMSManager.FarapayamakSend.SendSoap.SendSimpleSMS2(TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Request request) {
            return base.Channel.SendSimpleSMS2(request);
        }
        
        public string SendSimpleSMS2(string username, string password, string to, string from, string text, bool isflash) {
            TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Request inValue = new TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Request();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2RequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            TaavoniUT3SMSManager.FarapayamakSend.SendSimpleSMS2Response retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).SendSimpleSMS2(inValue);
            return retVal.Body.SendSimpleSMS2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.SendSmsResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.SendSms(TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public int SendSms(string username, string password, TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString to, string from, string text, bool isflash, string udh, ref TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recId, ref byte[] status) {
            TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            TaavoniUT3SMSManager.FarapayamakSend.SendSmsResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).SendSms(inValue);
            recId = retVal.Body.recId;
            status = retVal.Body.status;
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.SendWithDomain(TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequest request) {
            return base.Channel.SendWithDomain(request);
        }
        
        public string SendWithDomain(string username, string password, string to, string from, string text, bool isflash, string domainName) {
            TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.domainName = domainName;
            TaavoniUT3SMSManager.FarapayamakSend.SendWithDomainResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).SendWithDomain(inValue);
            return retVal.Body.SendWithDomainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetSmsPrice(TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequest request) {
            return base.Channel.GetSmsPrice(request);
        }
        
        public double GetSmsPrice(string username, string password, int irancellCount, int mtnCount, string from, string text) {
            TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.irancellCount = irancellCount;
            inValue.Body.mtnCount = mtnCount;
            inValue.Body.from = from;
            inValue.Body.text = text;
            TaavoniUT3SMSManager.FarapayamakSend.GetSmsPriceResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetSmsPrice(inValue);
            return retVal.Body.GetSmsPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetCreditResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetCredit(TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public double GetCredit(string username, string password) {
            TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            TaavoniUT3SMSManager.FarapayamakSend.GetCreditResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetCredit(inValue);
            return retVal.Body.GetCreditResult;
        }
        
        public int GetDelivery(long recId) {
            return base.Channel.GetDelivery(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Response TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetDelivery2(TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Request request) {
            return base.Channel.GetDelivery2(request);
        }
        
        public int GetDelivery2(string recId) {
            TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Request inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Request();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2RequestBody();
            inValue.Body.recId = recId;
            TaavoniUT3SMSManager.FarapayamakSend.GetDelivery2Response retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetDelivery2(inValue);
            return retVal.Body.GetDelivery2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetMultiDelivery(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequest request) {
            return base.Channel.GetMultiDelivery(request);
        }
        
        public byte[] GetMultiDelivery(string recId) {
            TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryRequestBody();
            inValue.Body.recId = recId;
            TaavoniUT3SMSManager.FarapayamakSend.GetMultiDeliveryResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetMultiDelivery(inValue);
            return retVal.Body.GetMultiDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Response TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetMultiDelivery2(TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Request request) {
            return base.Channel.GetMultiDelivery2(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfString GetMultiDelivery2(string recId) {
            TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Request inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Request();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2RequestBody();
            inValue.Body.recId = recId;
            TaavoniUT3SMSManager.FarapayamakSend.GetMultiDelivery2Response retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetMultiDelivery2(inValue);
            return retVal.Body.GetMultiDelivery2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetDeliveries(TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequest request) {
            return base.Channel.GetDeliveries(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakSend.ArrayOfInt GetDeliveries(TaavoniUT3SMSManager.FarapayamakSend.ArrayOfLong recIds, string username, string password) {
            TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesRequestBody();
            inValue.Body.recIds = recIds;
            inValue.Body.username = username;
            inValue.Body.password = password;
            TaavoniUT3SMSManager.FarapayamakSend.GetDeliveriesResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetDeliveries(inValue);
            return retVal.Body.GetDeliveriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.GetInboxCount(TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequest request) {
            return base.Channel.GetInboxCount(request);
        }
        
        public int GetInboxCount(string username, string password, bool isRead) {
            TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.isRead = isRead;
            TaavoniUT3SMSManager.FarapayamakSend.GetInboxCountResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).GetInboxCount(inValue);
            return retVal.Body.GetInboxCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.FarapayamakSend.getMessagesResponse TaavoniUT3SMSManager.FarapayamakSend.SendSoap.getMessages(TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequest request) {
            return base.Channel.getMessages(request);
        }
        
        public TaavoniUT3SMSManager.FarapayamakSend.MessagesBL[] getMessages(string username, string password, int location, string from, int index, int count) {
            TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequest inValue = new TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequest();
            inValue.Body = new TaavoniUT3SMSManager.FarapayamakSend.getMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.location = location;
            inValue.Body.from = from;
            inValue.Body.index = index;
            inValue.Body.count = count;
            TaavoniUT3SMSManager.FarapayamakSend.getMessagesResponse retVal = ((TaavoniUT3SMSManager.FarapayamakSend.SendSoap)(this)).getMessages(inValue);
            return retVal.Body.getMessagesResult;
        }
    }
}
