//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaavoniUT3SMSManager.GhasedakSMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Messages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((this.MessageIDField.Equals(value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecipientNumber {
            get {
                return this.RecipientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientNumberField, value) != true)) {
                    this.RecipientNumberField = value;
                    this.RaisePropertyChanged("RecipientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderNumber {
            get {
                return this.SenderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNumberField, value) != true)) {
                    this.SenderNumberField = value;
                    this.RaisePropertyChanged("SenderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReceiveDate {
            get {
                return this.ReceiveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveDateField, value) != true)) {
                    this.ReceiveDateField = value;
                    this.RaisePropertyChanged("ReceiveDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendType", Namespace="http://tempuri.org/")]
    public enum SendType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllNumbers = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RandomNumbers = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SortingNumbers = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        private System.DateTime sendDateField;
        
        private int totalSmsField;
        
        private int priceField;
        
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TaavoniUT3SMSManager.GhasedakSMSService.RequestDelivery[] deliveryReportField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string senderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.senderNumberField, value) != true)) {
                    this.senderNumberField = value;
                    this.RaisePropertyChanged("senderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime sendDate {
            get {
                return this.sendDateField;
            }
            set {
                if ((this.sendDateField.Equals(value) != true)) {
                    this.sendDateField = value;
                    this.RaisePropertyChanged("sendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int totalSms {
            get {
                return this.totalSmsField;
            }
            set {
                if ((this.totalSmsField.Equals(value) != true)) {
                    this.totalSmsField = value;
                    this.RaisePropertyChanged("totalSms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string statusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.statusDescriptionField, value) != true)) {
                    this.statusDescriptionField = value;
                    this.RaisePropertyChanged("statusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public TaavoniUT3SMSManager.GhasedakSMSService.RequestDelivery[] deliveryReport {
            get {
                return this.deliveryReportField;
            }
            set {
                if ((object.ReferenceEquals(this.deliveryReportField, value) != true)) {
                    this.deliveryReportField = value;
                    this.RaisePropertyChanged("deliveryReport");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDelivery", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RequestDelivery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long statusIdField;
        
        private long statusCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long statusId {
            get {
                return this.statusIdField;
            }
            set {
                if ((this.statusIdField.Equals(value) != true)) {
                    this.statusIdField = value;
                    this.RaisePropertyChanged("statusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long statusCount {
            get {
                return this.statusCountField;
            }
            set {
                if ((this.statusCountField.Equals(value) != true)) {
                    this.statusCountField = value;
                    this.RaisePropertyChanged("statusCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GhasedakSMSService.v2Soap")]
    public interface v2Soap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.SendSMSResponse SendSMS(TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageStatus", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusResponse GetMessageStatus(TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.GetCreditResponse GetCredit(TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMessageIDs", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsResponse CheckMessageIDs(TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReceiveMessages", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesResponse GetReceiveMessages(TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountForPostalCode", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeResponse GetCountForPostalCode(TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkSmsToPostalCode", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeResponse SendBulkSmsToPostalCode(TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkRequestInfo", ReplyAction="*")]
        TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoResponse GetBulkRequestInfo(TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString senderNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString recipientNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString messageBodies;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString sendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfInt messageClasses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong checkingMessageIds;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string username, string password, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString senderNumbers, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString recipientNumbers, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString messageBodies, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString sendDate, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfInt messageClasses, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong checkingMessageIds) {
            this.username = username;
            this.password = password;
            this.senderNumbers = senderNumbers;
            this.recipientNumbers = recipientNumbers;
            this.messageBodies = messageBodies;
            this.sendDate = sendDate;
            this.messageClasses = messageClasses;
            this.checkingMessageIds = checkingMessageIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(TaavoniUT3SMSManager.GhasedakSMSService.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatus", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequestBody Body;
        
        public GetMessageStatusRequest() {
        }
        
        public GetMessageStatusRequest(TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong MessageIDs;
        
        public GetMessageStatusRequestBody() {
        }
        
        public GetMessageStatusRequestBody(string username, string password, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong MessageIDs) {
            this.username = username;
            this.password = password;
            this.MessageIDs = MessageIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusResponseBody Body;
        
        public GetMessageStatusResponse() {
        }
        
        public GetMessageStatusResponse(TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfInt GetMessageStatusResult;
        
        public GetMessageStatusResponseBody() {
        }
        
        public GetMessageStatusResponseBody(TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfInt GetMessageStatusResult) {
            this.GetMessageStatusResult = GetMessageStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequestBody Body;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody() {
        }
        
        public GetCreditRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetCreditResponseBody Body;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(TaavoniUT3SMSManager.GhasedakSMSService.GetCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody() {
        }
        
        public GetCreditResponseBody(double GetCreditResult) {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMessageIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMessageIDs", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequestBody Body;
        
        public CheckMessageIDsRequest() {
        }
        
        public CheckMessageIDsRequest(TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckMessageIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong checkingids;
        
        public CheckMessageIDsRequestBody() {
        }
        
        public CheckMessageIDsRequestBody(string username, string password, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong checkingids) {
            this.username = username;
            this.password = password;
            this.checkingids = checkingids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckMessageIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckMessageIDsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsResponseBody Body;
        
        public CheckMessageIDsResponse() {
        }
        
        public CheckMessageIDsResponse(TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckMessageIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong CheckMessageIDsResult;
        
        public CheckMessageIDsResponseBody() {
        }
        
        public CheckMessageIDsResponseBody(TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong CheckMessageIDsResult) {
            this.CheckMessageIDsResult = CheckMessageIDsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiveMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiveMessages", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequestBody Body;
        
        public GetReceiveMessagesRequest() {
        }
        
        public GetReceiveMessagesRequest(TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReceiveMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int isRead;
        
        public GetReceiveMessagesRequestBody() {
        }
        
        public GetReceiveMessagesRequestBody(string username, string password, string destNumber, int isRead) {
            this.username = username;
            this.password = password;
            this.destNumber = destNumber;
            this.isRead = isRead;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiveMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiveMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesResponseBody Body;
        
        public GetReceiveMessagesResponse() {
        }
        
        public GetReceiveMessagesResponse(TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReceiveMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.Messages[] GetReceiveMessagesResult;
        
        public GetReceiveMessagesResponseBody() {
        }
        
        public GetReceiveMessagesResponseBody(TaavoniUT3SMSManager.GhasedakSMSService.Messages[] GetReceiveMessagesResult) {
            this.GetReceiveMessagesResult = GetReceiveMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountForPostalCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountForPostalCode", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequestBody Body;
        
        public GetCountForPostalCodeRequest() {
        }
        
        public GetCountForPostalCodeRequest(TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountForPostalCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string postalcode;
        
        public GetCountForPostalCodeRequestBody() {
        }
        
        public GetCountForPostalCodeRequestBody(string username, string password, string postalcode) {
            this.username = username;
            this.password = password;
            this.postalcode = postalcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountForPostalCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountForPostalCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeResponseBody Body;
        
        public GetCountForPostalCodeResponse() {
        }
        
        public GetCountForPostalCodeResponse(TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountForPostalCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetCountForPostalCodeResult;
        
        public GetCountForPostalCodeResponseBody() {
        }
        
        public GetCountForPostalCodeResponseBody(int GetCountForPostalCodeResult) {
            this.GetCountForPostalCodeResult = GetCountForPostalCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBulkSmsToPostalCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBulkSmsToPostalCode", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequestBody Body;
        
        public SendBulkSmsToPostalCodeRequest() {
        }
        
        public SendBulkSmsToPostalCodeRequest(TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendBulkSmsToPostalCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string postalcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string originator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public TaavoniUT3SMSManager.GhasedakSMSService.SendType sendType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime sendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int startIndex;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int count;
        
        public SendBulkSmsToPostalCodeRequestBody() {
        }
        
        public SendBulkSmsToPostalCodeRequestBody(string username, string password, string postalcode, string originator, string content, TaavoniUT3SMSManager.GhasedakSMSService.SendType sendType, System.DateTime sendDate, int startIndex, int count) {
            this.username = username;
            this.password = password;
            this.postalcode = postalcode;
            this.originator = originator;
            this.content = content;
            this.sendType = sendType;
            this.sendDate = sendDate;
            this.startIndex = startIndex;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBulkSmsToPostalCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBulkSmsToPostalCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeResponseBody Body;
        
        public SendBulkSmsToPostalCodeResponse() {
        }
        
        public SendBulkSmsToPostalCodeResponse(TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendBulkSmsToPostalCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendBulkSmsToPostalCodeResult;
        
        public SendBulkSmsToPostalCodeResponseBody() {
        }
        
        public SendBulkSmsToPostalCodeResponseBody(long SendBulkSmsToPostalCodeResult) {
            this.SendBulkSmsToPostalCodeResult = SendBulkSmsToPostalCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBulkRequestInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBulkRequestInfo", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequestBody Body;
        
        public GetBulkRequestInfoRequest() {
        }
        
        public GetBulkRequestInfoRequest(TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBulkRequestInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long requestId;
        
        public GetBulkRequestInfoRequestBody() {
        }
        
        public GetBulkRequestInfoRequestBody(string username, string password, long requestId) {
            this.username = username;
            this.password = password;
            this.requestId = requestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBulkRequestInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBulkRequestInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoResponseBody Body;
        
        public GetBulkRequestInfoResponse() {
        }
        
        public GetBulkRequestInfoResponse(TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBulkRequestInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaavoniUT3SMSManager.GhasedakSMSService.RequestInfo GetBulkRequestInfoResult;
        
        public GetBulkRequestInfoResponseBody() {
        }
        
        public GetBulkRequestInfoResponseBody(TaavoniUT3SMSManager.GhasedakSMSService.RequestInfo GetBulkRequestInfoResult) {
            this.GetBulkRequestInfoResult = GetBulkRequestInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface v2SoapChannel : TaavoniUT3SMSManager.GhasedakSMSService.v2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class v2SoapClient : System.ServiceModel.ClientBase<TaavoniUT3SMSManager.GhasedakSMSService.v2Soap>, TaavoniUT3SMSManager.GhasedakSMSService.v2Soap {
        
        public v2SoapClient() {
        }
        
        public v2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public v2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public v2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public v2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.SendSMSResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.SendSMS(TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong SendSMS(string username, string password, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString senderNumbers, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString recipientNumbers, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString messageBodies, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfString sendDate, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfInt messageClasses, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong checkingMessageIds) {
            TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.senderNumbers = senderNumbers;
            inValue.Body.recipientNumbers = recipientNumbers;
            inValue.Body.messageBodies = messageBodies;
            inValue.Body.sendDate = sendDate;
            inValue.Body.messageClasses = messageClasses;
            inValue.Body.checkingMessageIds = checkingMessageIds;
            TaavoniUT3SMSManager.GhasedakSMSService.SendSMSResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.GetMessageStatus(TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatus(request);
        }
        
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfInt GetMessageStatus(string username, string password, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong MessageIDs) {
            TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.MessageIDs = MessageIDs;
            TaavoniUT3SMSManager.GhasedakSMSService.GetMessageStatusResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).GetMessageStatus(inValue);
            return retVal.Body.GetMessageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.GetCreditResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.GetCredit(TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public double GetCredit(string username, string password) {
            TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            TaavoniUT3SMSManager.GhasedakSMSService.GetCreditResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).GetCredit(inValue);
            return retVal.Body.GetCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.CheckMessageIDs(TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequest request) {
            return base.Channel.CheckMessageIDs(request);
        }
        
        public TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong CheckMessageIDs(string username, string password, TaavoniUT3SMSManager.GhasedakSMSService.ArrayOfLong checkingids) {
            TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.checkingids = checkingids;
            TaavoniUT3SMSManager.GhasedakSMSService.CheckMessageIDsResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).CheckMessageIDs(inValue);
            return retVal.Body.CheckMessageIDsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.GetReceiveMessages(TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequest request) {
            return base.Channel.GetReceiveMessages(request);
        }
        
        public TaavoniUT3SMSManager.GhasedakSMSService.Messages[] GetReceiveMessages(string username, string password, string destNumber, int isRead) {
            TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.destNumber = destNumber;
            inValue.Body.isRead = isRead;
            TaavoniUT3SMSManager.GhasedakSMSService.GetReceiveMessagesResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).GetReceiveMessages(inValue);
            return retVal.Body.GetReceiveMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.GetCountForPostalCode(TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequest request) {
            return base.Channel.GetCountForPostalCode(request);
        }
        
        public int GetCountForPostalCode(string username, string password, string postalcode) {
            TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.postalcode = postalcode;
            TaavoniUT3SMSManager.GhasedakSMSService.GetCountForPostalCodeResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).GetCountForPostalCode(inValue);
            return retVal.Body.GetCountForPostalCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.SendBulkSmsToPostalCode(TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequest request) {
            return base.Channel.SendBulkSmsToPostalCode(request);
        }
        
        public long SendBulkSmsToPostalCode(string username, string password, string postalcode, string originator, string content, TaavoniUT3SMSManager.GhasedakSMSService.SendType sendType, System.DateTime sendDate, int startIndex, int count) {
            TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.postalcode = postalcode;
            inValue.Body.originator = originator;
            inValue.Body.content = content;
            inValue.Body.sendType = sendType;
            inValue.Body.sendDate = sendDate;
            inValue.Body.startIndex = startIndex;
            inValue.Body.count = count;
            TaavoniUT3SMSManager.GhasedakSMSService.SendBulkSmsToPostalCodeResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).SendBulkSmsToPostalCode(inValue);
            return retVal.Body.SendBulkSmsToPostalCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoResponse TaavoniUT3SMSManager.GhasedakSMSService.v2Soap.GetBulkRequestInfo(TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequest request) {
            return base.Channel.GetBulkRequestInfo(request);
        }
        
        public TaavoniUT3SMSManager.GhasedakSMSService.RequestInfo GetBulkRequestInfo(string username, string password, long requestId) {
            TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequest inValue = new TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequest();
            inValue.Body = new TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requestId = requestId;
            TaavoniUT3SMSManager.GhasedakSMSService.GetBulkRequestInfoResponse retVal = ((TaavoniUT3SMSManager.GhasedakSMSService.v2Soap)(this)).GetBulkRequestInfo(inValue);
            return retVal.Body.GetBulkRequestInfoResult;
        }
    }
}
